### ISSUE TITLE
Replace <i> with <q>

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/arnold-bennett_riceyman-steps#2]
https://github.com/johnrambow/arnold-bennett_riceyman-steps/blob/699a5d39137f17b13a8a273b5fa9c618da41dd79/src/epub/text/chapter-2-3.xhtml#L46

It’s a direct inline quote.

**Comment by johnrambow** [comment]
I wonder if this one shouldn't remain with italics tags, since it seems analogous to the want ad. It's in quotes and in italics, but it's not internal thoughts or being read out loud.
