### ISSUE TITLE
Abbreviation updates needed for this advert

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/arnold-bennett_riceyman-steps#3]
https://github.com/johnrambow/arnold-bennett_riceyman-steps/blob/699a5d39137f17b13a8a273b5fa9c618da41dd79/src/epub/text/chapter-1-13.xhtml#L47

- Missed abbreviations: Confec., wkly.
- WC and WC1 are postcodes, so need special treatment: https://standardebooks.org/manual/1.6.4/single-page#8.10.6

**Comment by johnrambow** [comment]
Fixed, thx.
